export const generateInvoicePDFBuffer = async (invoiceData: any): Promise<Buffer> => {
  // Simulates PDF generation of a GST Invoice
  const lines = [
    `==================================================`,
    `               GST TAX INVOICE                    `,
    `==================================================`,
    `Invoice Number: ${invoiceData.invoiceNumber}`,
    `Issue Date:     ${invoiceData.issueDate || new Date().toISOString().split('T')[0]}`,
    `Due Date:       ${invoiceData.dueDate}`,
    `--------------------------------------------------`,
    `Client Name:    ${invoiceData.clientName}`,
    `Client Address: ${invoiceData.clientAddress}`,
    `GSTIN:          ${invoiceData.clientGstin || 'Unregistered'}`,
    `--------------------------------------------------`,
    `ITEMS:`,
  ];

  if (invoiceData.items && Array.isArray(invoiceData.items)) {
    invoiceData.items.forEach((item: any, idx: number) => {
      lines.push(
        `${idx + 1}. ${item.description} (HSN/SAC: ${item.hsnSac || '—'})` +
        `   Qty: ${item.quantity} | Rate: INR ${item.rate} | GST: ${item.gstRate}%` +
        `   Line Total: INR ${item.total}`
      );
    });
  }

  lines.push(`--------------------------------------------------`);
  lines.push(`Tax Scheme:     ${invoiceData.gstType.toUpperCase()}`);
  lines.push(`Subtotal:       INR ${invoiceData.subtotal}`);
  lines.push(`CGST:           INR ${invoiceData.totalCgst}`);
  lines.push(`SGST:           INR ${invoiceData.totalSgst}`);
  lines.push(`IGST:           INR ${invoiceData.totalIgst}`);
  lines.push(`Total GST Tax:  INR ${invoiceData.totalGst}`);
  lines.push(`Grand Total:    INR ${invoiceData.total}`);
  lines.push(`==================================================`);
  lines.push(`Thank you for your business!`);
  lines.push(`Generated by Finance Copilot.`);
  lines.push(`==================================================`);

  const rawText = lines.join('\n');
  return Buffer.from(rawText, 'utf-8');
};
